# This is a config for E2B sandbox template.
# You can use template ID (wx3mieq4xcxhjzsr81qi) or template name (bloom-nextjs-sachikas-1678-v3) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("bloom-nextjs-sachikas-1678-v3") # Sync sandbox
# sandbox = await AsyncSandbox.create("bloom-nextjs-sachikas-1678-v3") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('bloom-nextjs-sachikas-1678-v3')

team_id = "6d0ee7d4-fda6-4ad8-aa03-113e567c27d0"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "bloom-nextjs-sachikas-1678-v3"
template_id = "wx3mieq4xcxhjzsr81qi"
